name: Test & Lint

on:
  push:
    branches:
      - 'master'
    paths:
      - 'packages/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'packages/**'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm i
      - run: pnpm run check
        env:
          CI: true
